### ISSUE TITLE
内存页面-链接跳转404

### ISSUE THREAD

**Issue by vsona** [liteli1987gmail/langchainzh#2]
https://www.langchain.asia/modules/memory

![image](https://github.com/liteli1987gmail/langchainzh/assets/10459894/5a2a1d32-f157-4361-93c4-473d4f1a1dd9)
这几个都是404

**Comment by liteli1987gmail** [comment]
感谢指出，已修复。 记忆内存这里，文档主要提供的是#类型和#示例的文档，删除了检索和操作、存储三个跳转。
