### ISSUE TITLE
探索Milvus SDK的API参考  api跳转404

### ISSUE THREAD

**Issue by create-co** [liteli1987gmail/langchainzh#3]
https://www.milvus-io.com/search
https://www.milvus-io.com/api-reference/java/v2.2.5/About
![image](https://github.com/liteli1987gmail/langchainzh/assets/132736315/5f34c110-bf3a-4bc1-80a9-8adbb5cce686)

**Comment by liteli1987gmail** [comment]
已修复~感谢
