### ISSUE TITLE
Feedback for “自定义代理人”

### ISSUE THREAD

**Issue by b3601993** [liteli1987gmail/langchainzh#4]
![image](https://github.com/liteli1987gmail/langchainzh/assets/9765169/ec3dac30-86bd-41e7-adc7-68d47091275e)

有个地方翻译错误：原文地址：https://python.langchain.com/docs/modules/agents/how_to/custom_agent

**Comment by liteli1987gmail** [comment]
感谢~~已修复。

一个代理 (Agent) 由二个部分组成：
- 工具 tool：代理可以使用的工具。
- 代理执行器 ：这决定了采取哪些行动。
